Algoritmo "idade"
Var
ano_atual, ano_nascimento, idade : inteiro



Inicio
Escreval("Digite em que ano estamos")

leia (ano_atual)

Escreval ("Agora digite em que ano você nasceu")

leia (ano_nascimento)

idade <- (ano_atual - ano_nascimento)

Escreval("você tem ", idade, " anos")

SE (idade >= 18) entao

Escreval("Você é maior de idade!")

SENAO

Escreval("Você é menor de idade!")

Fimse


Fimalgoritmo