Algoritmo "Exercício_01"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 29/09/2024
Var
n1, n2, soma : real


Inicio
escreval("Digite o primeiro número")
leia(n1)
escreval("Digite o segundo número")
leia(n2)

soma <- n1 + n2

escreva("A soma dos números digitados é: ", soma)

Fimalgoritmo